### ISSUE TITLE
Data also available per day?

### ISSUE THREAD

**Issue by tomwenseleers** [covid-19-Re/variantPlot#2]
Is the data from the Risch lab also available per day? At https://ispmbern.github.io/covid-19/variants/ https://ispmbern.github.io/covid-19/variants/data/variants_GE.csv I saw that the Viollier lab data are given per day, but is such data also available for the Risch lab that you know of perhaps?

**Comment by chaoran-chen** [comment]
We work on providing the Risch data on a per-day basis and will put it either here or release the data on another channel.

**Comment by chaoran-chen** [comment]
Hi @tomwenseleers, sorry that I didn't update you earlier: daily data can now be found in https://github.com/cevo-public/Quantification-of-the-spread-of-a-SARS-CoV-2-variant.
